config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root 'pages#index'
  get '/admin-page', to: 'pages#admin'
  get '/admin-phone-list', to: 'pages#adminphones'

  resources :phones do
    resources :ordernoregs
    resources :comments
  end
  resources :userparams
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :phones
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :phone
  belongs_to :user

  validates :body, presence: true
end

app/models/ordernoreg.rb
class Ordernoreg < ApplicationRecord
  belongs_to :phone

  validates :count, :mobnumber, :email, :adress, presence: :true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :admin
  has_many :ordernoregs
  has_many :comments

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :price, :brand, :model, :materials, :color, :os, :displaysize, :displaytype, :displayresolution, :soc, :frequency, :gpu, :rom, :ram, :sims, :maincam, :frontcam, :videoresolution, :focus, :moreaboutcam, :battery, :fastcharge, :wireless, :year, :interfaces, :dimensions, :mass, :more, :description, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_one :userparam
end

app/models/userparam.rb
class Userparam < ApplicationRecord
  belongs_to :user
  validates :name, :mobnumber, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_phone
    before_action :authenticate_user!
    before_action :check

    def new
      @b = false
      @phone.comments.each do |c|
        if c.user.id == current_user.id
          @b = true
        end
      end

      if @b == false
        @comment = Comment.new
      else
        flash[:notice] = "You have already been added a comment."
        redirect_to phone_path(@phone.id)
      end
    end

    def create
      params[:comment][:phone_id] = @phone.id
      @comment = current_user.comments.build(comment_params)
      if @comment.save
        redirect_to phone_path(@phone.id)
      else
        flash[:error] = "Comment has error"
        render 'new'
      end
    end

    def edit
      @comment = Comment.find_by(id: params[:id])
    end

    def update
      @comment = Comment.find_by(id: params[:id])
      params[:comment][:phone_id] = @phone.id
      if @comment.update(comment_params)
        flash[:notice] = "Comment successfully updated"
        redirect_to phone_path(@phone.id)
      else
        flash[:error] = "Comment has error"
        render 'edit'
      end

    end

    def destroy
      @comment = Comment.find_by(id: params[:id])
      @comment.destroy
      redirect_to phone_path(@phone.id)
    end

  private

    def comment_params
      params.require(:comment).permit(:phone_id, :user_id, :body)
    end

    def find_phone
      @phone = Phone.find_by(id: params[:phone_id])
    end

    def check
      if user_signed_in?
        sign_out :admin
      end
    end
end

app/controllers/ordernoregs_controller.rb
class OrdernoregsController < ApplicationController
  before_action :check

    def new
      @phone = Phone.find_by(id: params[:phone_id])
      @order = Ordernoreg.new
    end

    def create
      @phone = Phone.find_by(id: params[:phone_id])
      params[:ordernoreg][:phone_id] = @phone.id
      @order = Ordernoreg.new(order_params)
      if @order.save
        redirect_to root_path
      else
        flash[:error] = "Order has error"
        render 'new'
      end
    end

  private

    def order_params
      params.require(:ordernoreg).permit(:phone_id, :count, :mobnumber, :email, :adress)
    end

    def check
      if user_signed_in?
        sign_out :admin
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin!, only: [:admin, :adminphones]
  def index
    @phones = Phone.all
    if user_signed_in?
      sign_out :admin
    end

    if user_signed_in? && current_user.userparam.nil?
      redirect_to new_userparam_path
    end
  end

  def adminphones
    @phones = Phone.all
  end

  def admin
    sign_out :user
    @orders = Ordernoreg.all
  end

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  before_action :check
  def new
    @phone = Phone.new
  end

  def create
    @phone = current_admin.phones.build(phone_params)
    if @phone.save
      redirect_to admin_page_path
    else render 'new'
    end
  end

  def show
    @phone = Phone.find(params[:id])
    @comments = @phone.comments
  end

  def edit
    @phone = Phone.find(params[:id])
  end

  def update
    @phone = Phone.find(params[:id])
    @phone.update(phone_params)
    if @phone.save
      redirect_to phone_path(@phone.id)
    else render 'edit'
    end
  end

  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy
    redirect_to admin_page_path
  end

  private
    def phone_params
      params.require(:phone).permit(:admin_id, :photo, :price, :brand, :model, :materials, :color, :os, :displaysize, :displaytype, :displayresolution, :soc, :frequency, :gpu, :rom, :ram, :sims, :maincam, :frontcam, :videoresolution, :focus, :moreaboutcam, :battery, :fastcharge, :wireless, :year, :interfaces, :dimensions, :mass, :more, :description)
    end

    def check
      if user_signed_in?
        sign_out :admin
      end
    end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
  before_action :authenticate_user!
    def new
      @userparam = Userparam.new
    end

    def create
      @userparam = current_user.build_userparam(userparam_params)
      if @userparam.save
        redirect_to root_path
      else
        flash[:error] = "Userparam has error"
        render 'new'
      end
    end

    def edit
      @userparam = Userparam.find_by(user_id: current_user.id)
    end

    def update
      @userparam = Userparam.find_by(user_id: current_user.id)
      if @userparam.update(userparam_params)
        flash[:notice] = "Userparam successfully updated"
        redirect_to root_path
      else
        flash[:error] = "Userparam has error"
        render 'edit'
      end

    end

  private

    def userparam_params
      params.require(:userparam).permit(:user_id, :name, :mobnumber)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ordernoregs_helper.rb
module OrdernoregsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' && Admin.size < 1 %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/comments/edit.html.erb
<div style="margin-top: 40px"/>
<h2>Update comment for <%= @phone.brand %> <%= @phone.model %></h2>
<%= form_for @comment, url: phone_comment_path(@comment.id) do |f| %>
Enter your text here:<br>
<%= f.text_area :body, size: "60x12" %><br />
<%= f.submit "Save" %>
<% end %>

app/views/comments/new.html.erb
<div style="margin-top: 40px"/>
<h2>Comment for <%= @phone.brand %> <%= @phone.model %></h2>
<%= form_for @comment, url: phone_comments_path(@phone.id) do |f| %>
Enter your text here:<br>
<%= f.text_area :body, size: "60x12" %><br />
<%= f.submit "Add comment" %>
<% end %>

app/views/layouts/_header.html.erb
<div style="top: 0px; left: 0px; width: 100%;
    position: fixed;
    top: 0px;
    left: 0px;
    padding: 4px;
    background-color: white;
    border-bottom-left-radius: 16px;
    border-bottom-right-radius: 16px;
    vertical-align: middle;
    box-shadow: 4px 2px 7px 3px rgba(0, 0, 0, 0.44);">
    <% if admin_signed_in? %>
        <%= link_to admin_page_path do %><strong><%= current_admin.email %></strong><% end %> <%= link_to "Home", root_path %> <%= link_to "Profile", edit_admin_registration_path %> <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
        <%= link_to "View phones", admin_phone_list_path %>
    <% end %>
    <% if user_signed_in? %>
        <% if !current_user.userparam.nil? %><strong><%= current_user.userparam.name %></strong> <%= link_to "Home", root_path %> <%= link_to "Profile", edit_userparam_path(current_user.userparam.id) %><%end%> <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "Sign in or sign up", new_user_session_path %>
    <% end %>
</div>
<div style="margin-top: 40px"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartphone Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <% flash.each do |name, message| %>
    <p><i><%= "#{name}: #{message}" %></i></p>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/ordernoregs/new.html.erb
<div style="margin-top: 40px"/>
<h2>Order for <%= @phone.brand %> <%= @phone.model %></h2>
<%= form_for @order, url: phone_ordernoregs_path(@phone.id) do |f| %>
Your phone number:
<%= f.number_field :mobnumber %><br>
Email:
<%= f.text_field :email %><br>
Your adress:
<%= f.text_field :adress %><br>
Count:
<%= f.number_field :count %><br>

<p>[Details about delivery...]</p>

<%= f.submit "Order" %>
<% end %>

app/views/pages/admin.html.erb
<h2 style="margin-top: 40px">Current orders</h2>


<p>
  <% @orders.each do |order| %>
    <%= order.phone.brand %> <%= order.phone.model %> <%= order.count %> <%= order.email %> <%= order.mobnumber %> <%= order.adress %><br>
    <hr>
  <% end %>
</p>

app/views/pages/adminphones.html.erb
<h2 style="margin-top: 40px">Smartphones</h2>
<p><%= link_to "Add phone", new_phone_path %><br>
<% if @phones == [] %>
    <p>No phones</p>
<% else %>
    <% @phones.each do |phone| %>
       <p><b><%= phone.brand %></b> <%= phone.model %> | <i><%= phone.price %> UAN</i> <%= link_to "Show", phone_path(phone.id) %> <%= link_to "Edit", edit_phone_path(phone.id) %> <%= link_to "Delete", phone_path(phone.id), method: :delete %><br>
    <% end %>
<% end %>

app/views/pages/index.html.erb
<h1>Smartphone Shop</h1>
<p><% @phones.each do |phone| %>
        <%= image_tag phone.photo.url(:medium) %><br>
       <%= link_to phone_path(phone.id) do %><p><b><%= phone.brand %></b> <%= phone.model %><%end%> | <i><%= phone.price %> UAN</i>
    <% end %>
</p>

app/views/phones/edit.html.erb
<div style="margin-top: 40px"/>
<%= form_for @phone, url: phone_path do |f| %>

<% if @phone.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @phone.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
Photo:
<%= f.file_field :photo %><br>
Brand:
<%= f.text_field :brand %><br>
Model:
<%= f.text_field :model %><br>
Price:
<%= f.number_field :price %><br>
Materials:
<%= f.text_field :materials %><br>
Color:
<%= f.text_field :color %><br>
OS:
<%= f.text_field :os %><br>
Display diagonal (inches):
<%= f.text_field :displaysize %><br>
Display type:
<%= f.text_field :displaytype %><br>
Display resolution:
<%= f.text_field :displayresolution %><br>
System on a Chip:
<%= f.text_field :soc %><br>
Frequency:
<%= f.text_field :frequency %><br>
GPU:
<%= f.text_field :gpu %><br>
ROM storage:
<%= f.number_field :rom %><br>
RAM storage:
<%= f.number_field :ram %><br>
Number of SIM cards:
<%= f.number_field :sims %><br>
Main camera:
<%= f.text_field :maincam %><br>
Front camera:
<%= f.text_field :frontcam %><br>
Video resolution:
<%= f.text_field :videoresolution %><br>
Camera focus type:
<%= f.text_field :focus %><br>
More about cam:
<%= f.text_area :moreaboutcam, size: "60x12" %><br>
Battery size (mAh):
<%= f.number_field :battery %><br>
Fast charge:
<%= f.text_field :fastcharge %><br>
Wireless interfaces:
<%= f.text_area :wireless, size: "60x12" %><br>
Wire interfaces:
<%= f.text_field :interfaces %><br>
Year:
<%= f.number_field :year %><br>
Dimensions:
<%= f.text_field :dimensions %><br>
Mass:
<%= f.number_field :mass %><br>
More:
<%= f.text_area :more, size: "60x12" %><br>
Description:
<%= f.text_area :description, size: "60x12" %><br>
<%= f.submit "Submit" %>
<% end %>

app/views/phones/new.html.erb
<div style="margin-top: 40px"/>
<%= form_for @phone, url: {action: "create"} do |f| %>

<% if @phone.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @phone.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
Photo:
<%= f.file_field :photo %><br>
Brand:
<%= f.text_field :brand %><br>
Model:
<%= f.text_field :model %><br>
Price:
<%= f.number_field :price %><br>
Materials:
<%= f.text_field :materials %><br>
Color:
<%= f.text_field :color %><br>
OS:
<%= f.text_field :os %><br>
Display diagonal (inches):
<%= f.text_field :displaysize %><br>
Display type:
<%= f.text_field :displaytype %><br>
Display resolution:
<%= f.text_field :displayresolution %><br>
System on a Chip:
<%= f.text_field :soc %><br>
Frequency:
<%= f.text_field :frequency %><br>
GPU:
<%= f.text_field :gpu %><br>
ROM storage:
<%= f.number_field :rom %><br>
RAM storage:
<%= f.number_field :ram %><br>
Number of SIM cards:
<%= f.number_field :sims %><br>
Main camera:
<%= f.text_field :maincam %><br>
Front camera:
<%= f.text_field :frontcam %><br>
Video resolution:
<%= f.text_field :videoresolution %><br>
Camera focus type:
<%= f.text_field :focus %><br>
More about cam:
<%= f.text_area :moreaboutcam, size: "60x12" %><br>
Battery size (mAh):
<%= f.number_field :battery %><br>
Fast charge:
<%= f.text_field :fastcharge %><br>
Wireless interfaces:
<%= f.text_area :wireless, size: "60x12" %><br>
Wire interfaces:
<%= f.text_field :interfaces %><br>
Year:
<%= f.number_field :year %><br>
Dimensions:
<%= f.text_field :dimensions %><br>
Mass:
<%= f.number_field :mass %><br>
More:
<%= f.text_area :more, size: "60x12" %><br>
Description:
<%= f.text_area :description, size: "60x12" %><br>
<%= f.submit "Add" %>
<% end %>

app/views/phones/show.html.erb
<div style="margin-top: 40px"/>
<h2><%= @phone.brand %> <%= @phone.model %></h2>
<%= image_tag @phone.photo.url(:medium) %><br>
<%= @phone.price %> UAN <br>
<p><h3>Description:</h3></p>
<%= @phone.description %>
<p>Configuration:<p>
Materials:
<%= @phone.materials %><br>
Color:
<%= @phone.color %><br>
OS:
<%= @phone.os %><br>
Display size:
<%= @phone.displaysize %><br>
Display type:
<%= @phone.displaytype %><br>
Display resolution:
<%= @phone.displayresolution %><br>
Proceccor:
<%= @phone.soc %><br>
Frequency:
<%= @phone.frequency %><br>
GPU:
<%= @phone.gpu %><br>
Memory capacity:
<%= @phone.rom %> GB<br>
RAM capacity:
<%= @phone.ram %> GB <br>
Number of SIM cards:
<%= @phone.sims %><br>
Main camera:
<%= @phone.maincam %><br>
Front camera:
<%= @phone.frontcam %><br>
Video resolution:
<%= @phone.videoresolution %><br>
Camera focus type:
<%= @phone.focus %><br>
More about camera:
<%= @phone.moreaboutcam %><br>
Battery capacity:
<%= @phone.battery %> mAh<br>
Fast charge:
<%= @phone.fastcharge %><br>
Wireless interfaces:
<%= @phone.wireless %><br>
Year:
<%= @phone.year %><br>
Wire interfaces:
<%= @phone.interfaces %><br>
Dimensions:
<%= @phone.dimensions %><br>
Mass:
<%= @phone.mass %><br>
More:
<%= @phone.more %><br>
<% if !admin_signed_in? %>
    <p><%= link_to "Buy", new_phone_ordernoreg_path(@phone.id) %></p><%end%>
<h3>Comments</h3><hr>
<%= link_to "Add comment", new_phone_comment_path(@phone.id) %><br>

<% @comments.each do |c| %>
    <p><b><%= c.user.userparam.name %></b></p>
    <p><%= c.body %></p>
    <% if user_signed_in? && c.user.id == current_user.id %>
      <%= link_to "Edit", edit_phone_comment_path(c.id) %>
      <%= link_to "Delete", phone_comment_path(c.id), method: :delete %>
    <%end%>
    <hr>
  <%end%>

app/views/userparams/edit.html.erb
<%= form_for @userparam, url: userparam_path(current_user.id) do |f| %>

  <% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  Name: <%= f.text_field :name %><br />
  Phone number: <%= f.number_field :mobnumber %><br />

  <%= f.submit "Update" %>
<% end %>

app/views/userparams/new.html.erb
<h1>Create Userparam</h1>
<%= form_for @userparam, url: userparams_path do |f| %>

<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  Name: <%= f.text_field :name %><br />
  Phone number: <%= f.number_field :mobnumber %><br />
  <%= f.submit "Create" %>
<% end %>